//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthCo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class earthcoEntities : DbContext
    {
        public earthcoEntities()
            : base("name=earthcoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccessLevel> tblAccessLevels { get; set; }
        public virtual DbSet<tblController> tblControllers { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblEstimateStatu> tblEstimateStatus { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblPunchlist> tblPunchlists { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSRFile> tblSRFiles { get; set; }
        public virtual DbSet<tblSRItem> tblSRItems { get; set; }
        public virtual DbSet<tblSRStatu> tblSRStatus { get; set; }
        public virtual DbSet<tblSRType> tblSRTypes { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblIrrigation> tblIrrigations { get; set; }
        public virtual DbSet<tblPunchlistDetail> tblPunchlistDetails { get; set; }
        public virtual DbSet<tblPunchlistItem> tblPunchlistItems { get; set; }
        public virtual DbSet<tblEstimateItem> tblEstimateItems { get; set; }
        public virtual DbSet<tblEstimate> tblEstimates { get; set; }
        public virtual DbSet<tblWeeklyReport> tblWeeklyReports { get; set; }
        public virtual DbSet<tblWeeklyReportFile> tblWeeklyReportFiles { get; set; }
        public virtual DbSet<tblEstimateFile> tblEstimateFiles { get; set; }
        public virtual DbSet<tblMonthlyLandsacpe> tblMonthlyLandsacpes { get; set; }
        public virtual DbSet<tblCustomerType> tblCustomerTypes { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<tblServiceLocation> tblServiceLocations { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
        public virtual DbSet<tblServiceRequest> tblServiceRequests { get; set; }
        public virtual DbSet<tblPurchaseOrderFile> tblPurchaseOrderFiles { get; set; }
        public virtual DbSet<tblPurchaseOrderItem> tblPurchaseOrderItems { get; set; }
        public virtual DbSet<tblPurchaseOrderStatu> tblPurchaseOrderStatus { get; set; }
        public virtual DbSet<tblBill> tblBills { get; set; }
        public virtual DbSet<tblBillFile> tblBillFiles { get; set; }
        public virtual DbSet<tblBillItem> tblBillItems { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblInvoiceFile> tblInvoiceFiles { get; set; }
        public virtual DbSet<tblInvoiceItem> tblInvoiceItems { get; set; }
        public virtual DbSet<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
    }
}
