//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItem()
        {
            this.tblEstimateItems = new HashSet<tblEstimateItem>();
            this.tblBillItems = new HashSet<tblBillItem>();
            this.tblInvoiceItems = new HashSet<tblInvoiceItem>();
            this.tblPunchlistItems = new HashSet<tblPunchlistItem>();
            this.tblPurchaseOrderItems = new HashSet<tblPurchaseOrderItem>();
            this.tblSRItems = new HashSet<tblSRItem>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> isSale { get; set; }
        public Nullable<bool> isPurchase { get; set; }
        public string SaleDescription { get; set; }
        public string PurchaseDescription { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public string SaleTaxCode { get; set; }
        public string PurchareTaxCode { get; set; }
        public Nullable<int> IncomeAccount { get; set; }
        public Nullable<int> ExpenseAccount { get; set; }
        public string Type { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccount tblAccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstimateItem> tblEstimateItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillItem> tblBillItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoiceItem> tblInvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPunchlistItem> tblPunchlistItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderItem> tblPurchaseOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSRItem> tblSRItems { get; set; }
    }
}
