//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPunchlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPunchlist()
        {
            this.tblPunchlistDetails = new HashSet<tblPunchlistDetail>();
        }
    
        public int PunchlistId { get; set; }
        public string Title { get; set; }
        public int StatusId { get; set; }
        public int CustomerId { get; set; }
        public int ServiceLocationId { get; set; }
        public int ContactId { get; set; }
        public int AssignedTo { get; set; }
        public int ServiceRequestId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblServiceRequest tblServiceRequest { get; set; }
        public virtual tblPunchlistStatu tblPunchlistStatu { get; set; }
        public virtual tblServiceLocation tblServiceLocation { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPunchlistDetail> tblPunchlistDetails { get; set; }
    }
}
