//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSyncLog
    {
        public int SyncLogId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> QBId { get; set; }
        public string Operation { get; set; }
        public string Message { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> isSync { get; set; }
        public Nullable<bool> isQB { get; set; }
    }
}
