//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeklyReportRC
    {
        public int WeeklyReportRCId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> ServiceLocationId { get; set; }
        public string CustomerName { get; set; }
        public string ContactName { get; set; }
        public string ContactCompany { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> RegionalManagerId { get; set; }
        public Nullable<System.DateTime> ReportForWeekOf { get; set; }
        public Nullable<bool> Didyoucheckthehealthofalltheplantsandtreesontheproperty { get; set; }
        public Nullable<bool> Didyouremovealldeceasedplantsortrees { get; set; }
        public Nullable<bool> Didyoucheckirrigationtomakesureallplantsarereceivingwater { get; set; }
        public Nullable<bool> Didyoucheckirrigationclock { get; set; }
        public Nullable<bool> Didyoufixallleaksorflooding { get; set; }
        public Nullable<bool> Weretheweedspulledorsprayed { get; set; }
        public Nullable<bool> Wasthetrashanddebriscollectedandproperlydisposedof { get; set; }
        public Nullable<bool> Didthedoorentrywayplantersgetaddressed { get; set; }
        public Nullable<bool> Didtheparkinglotgetcleaned { get; set; }
        public Nullable<bool> Isthemulchsufficient { get; set; }
        public string Arethereanyareasofconcern { get; set; }
        public string Describethemulchconditionandifweneedtoaddany { get; set; }
        public string Describetheentrancecondition { get; set; }
        public string Describethedrivethroughcondition { get; set; }
        public string Describetheperimeterofbuildingincludingsignagestreetfacingplantersetccondition { get; set; }
        public string Anyadditionalnotesmanagementshouldbeawareof { get; set; }
        public string SignatureofRConsitemanager { get; set; }
        public string NameofRConsitemanager { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblServiceLocation tblServiceLocation { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
