//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeklyReportRCFile
    {
        public int WeeklyReportRCFileId { get; set; }
        public string FileName { get; set; }
        public string Caption { get; set; }
        public string FilePath { get; set; }
        public string Share { get; set; }
        public Nullable<int> WeeklyReportRCId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tblWeeklyReportRC tblWeeklyReportRC { get; set; }
    }
}
